<?php
  $lang['number']		= 'Reference nr.';
  $lang['date'] 		= 'Dato';
  $lang['time']			= 'Tidspunkt';
  $lang['due'] 			= 'Betalingsfrist';
  $lang['to'] 			= '';
  $lang['from'] 		= '';
  $lang['product'] 		= 'Produkt';
  $lang['qty'] 			= 'Antal';
  $lang['price'] 		= 'Pris';
  $lang['discount'] 	= 'Rabat';
  $lang['vat'] 			= '';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Side';
  $lang['page_of'] 		= 'af';
?>